Allow SSL use
Since quite some time, I always get a "PostgreSQL SSL support: Missing"
message after configure. config.log shows this:

configure:5737: gcc -o conftest -g -O2   -L/opt/postgresql-head/lib
conftest.c -lpq   >&5
/usr/bin/ld: /tmp/ccAr1HM4.o: undefined reference to symbol
'SSL_connect'
/usr/bin/ld: note: 'SSL_connect' is defined in
DSO /usr/lib64/libssl.so.10 so try adding it to the linker command line
/usr/lib64/libssl.so.10: could not read symbols: Invalid operation
collect2: ld returned 1 exit status

Adding -lssl makes it work. SSL is detected, and the compilation take SSL into
account.

Fixes https://bugs.launchpad.net/ubuntu/+source/pgadmin3/+bug/780565